a=-1
#报错
assert a>0,"a超出范围"
#正常运行
assert a<0

# 报错类型为AssertionError	断言语句失败